FROM python:3.8-alpine

COPY ./turbo_api_creds-1.1.0-py3-none-any.whl /tmp/turbo_api_creds-1.1.0-py3-none-any.whl

RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev && \
    pip install /tmp/turbo_api_creds-1.1.0-py3-none-any.whl && \
    pip install vmtconnect && \
    pip install vmtplan && \
    pip install umsg && \
    pip install dateutils && \
    pip install pyyaml && \
    apk del --no-network .build-deps && \
    rm -rf /tmp/*
