FROM registry.access.redhat.com/ubi8/python-38

USER 0

RUN buildDeps='gcc' && \
    yum -y install $buildDeps && \
    pip install --upgrade pip && \
    pip install 'vmtconnect>3.6,<4' && \
    pip install 'vmtplan>2.2,<3' && \
    pip install 'umsg>=1,<2' && \
    pip install dateutils && \
    pip install 'pyyaml>5.3,<6' && \
    yum -y remove $buildDeps && \
    yum -y clean all --enablerepo='*' && \
    rm -rf /tmp/*

  USER 1001
