FROM python:3.8-alpine

RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev rust cargo && \
    pip install --upgrade pip && \
    pip install 'vmtconnect>3.2,<4' && \
    pip install 'vmtplan>2.2,<3' && \
    pip install 'umsg>=1,<2' && \
    pip install dateutils && \
    pip install 'pyyaml>5.3,<6' && \
    pip cache purge && \
    apk del --no-network .build-deps && \
    rm -rf /tmp/*
